### ISSUE TITLE
DOMInstr.js

### ISSUE THREAD

**Issue by leeoniya** [marvinhagemeister/dom-callcount#3]
hey @marvinhagemeister 

i wrote something similar that i use to test domvm: https://github.com/leeoniya/domvm/blob/3.x-dev/test/dominstr.js

domvm's `dev` build integrates it too for logging mutations.

first commit was actually back in Nov 2015: https://github.com/leeoniya/domvm/commits/1.x-dev/test/lib/dominstr.js

wonder if the ivi utils one was inspired by it? seems plausible ;)

**Comment by marvinhagemeister** [comment]
@leeoniya yep, the ivi-utils where the main inspiration. Needed something like this as a standalone module for another project at work where we check which Dom apis we are calling (for testing only). My first try was with the native `MutationObserver` API but personally I found it overly complex for this use case. That's when I had the idea to check if any vdom libraries had docs it differently and found the ivi-utils (mainly `ivi/tests/utils/dom.ts`).

The implementation you just linked to looks even more complete and more fledged out. Would you be interested in extracting it to its own package?

**Comment by leeoniya** [comment]
i'd prolly want to polish the API a bit first since it's not ideal to instrument/uninstrument on every start/end call. it would be good to add an option for persistent instrumentation and have start/end simply reset the counters. or maybe an explicit `.on()`/`.off()` pair.
